var name = "Henk";
var strength = 100;
var dollars = 0;
var weapon = "friendship";
var vehicle = "Volkswagen";
var addiction = "Waifu body pillows";
var friends = false;
var wanted = true;
var attitude = "stoned";
var rizz = false;
var speed = "sonic, gotta go fast";

console.log("name: " + name);
console.log("strength: " + strength);
console.log("dollars: " + dollars);
console.log("weapon: " + weapon);
console.log("vehicle: " + vehicle);
console.log("addiction: " + addiction);
console.log("friends: " + friends);
console.log("wanted: " + wanted);
console.log("attitude: " + attitude);
console.log("rizz: " + rizz);
console.log("speed: " + speed);